<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <LangVersion>14.0</LangVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>